install_apache:
  needs: run_ansible_lint
  runs-on: self-hosted
  steps:
  - name: Installing apache
    run: |
      workdir=“${GITHUB_WORKSPACE}”
      ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -u ubuntu -i
      $workdir/host_inventory $workdir/playbooks/apache-install.yml --private-key
‘/home/ubuntu/.ssh/vm-instance-key.pem’
  slack_on_failure:
    runs-on: self-hosted
    needs: [repo_updated, install_ansible, install_ansible_lint, run_ansible_lint,
  install_apache, website-update, website-test]
     if: ${{ failure() && (needs.repo_updated.result == 'failure' || needs.install_ansible.result
   == 'failure' || needs.install_ansible_lint.result == 'failure' || needs.run_ansible_lint.result ==
   'failure' || needs.install_apache.result == 'failure' || needs.website-update.result == 'failure'
    || needs.website-test.result == 'failure') }}
       steps:
        - name: Send Slack notification on failure
          uses: slackapi/slack-github-action@v1.24.0
          with:
            payload: |
             {
              "text": "GitHub Action pipeline failed!",
              "blocks": [
                {
              "type": "section",
              "text": {
              "type": "mrkdwn",
              "text": "GitHub Action pipeline failed!"
             }
            }
          ]
         }
       env:
         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
